
TARGET_ENV = x11
#TARGET_ENV = raspi


# ---------------------------------------
#  for X11
# ---------------------------------------
ifeq ($(TARGET_ENV), x11)
WINSYS_SRC = winsys_x11
LDFLAGS    +=
LIBS       += -lm -lEGL -lGLESv2
LIBS       +=  -lX11
CFLAGS     +=
CXXFLAGS   += -std=c++11
endif


# ---------------------------------------
#  for Raspberry Pi
# ---------------------------------------
ifeq ($(TARGET_ENV), raspi)
WINSYS_SRC = winsys_raspi
INCLUDES   += -I$(SDKSTAGE)/opt/vc/include/
LDFLAGS    += -L$(SDKSTAGE)/opt/vc/lib/
LIBS       += -lm -lbrcmEGL -lbrcmGLESv2
LIBS       += -lopenmaxil -lbcm_host
CFLAGS     +=
CXXFLAGS   += -std=c++11
endif
