include ../../Makefile.env

TARGET = socktest

SRCS =
SRCS += server_main.c
SRCS += ../../common/util_socket.c

OBJS =
OBJS += $(SRCS:%.c=./%.o)

INCLUDES += -I../../common
INCLUDES +=

CFLAGS   +=

LDFLAGS  +=
LIBS     +=

include ../../Makefile.include
